name: 🚀 Deploy to live on push
on:
 push:
  branches: main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.smti.e-businessclinic.com
        username: u260743870.somiti
        password: ${{ secrets.FTP_PASSWORD }}
