name: 🚀 Deploy to bikrihoy.com on push
on:
 push:
  branches: bikrihoy.com

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.paleturquoise-deer-392174.hostingersite.com
        username: u260743870.somoti
        password: ${{ secrets.FTP_PASSWORD }}
